// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bulbview.recipeplanner.domain;

import com.bulbview.recipeplanner.domain.Ingredient;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect IngredientDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IngredientDataOnDemand: @Component;
    
    private Random IngredientDataOnDemand.rnd = new SecureRandom();
    
    private List<Ingredient> IngredientDataOnDemand.data;
    
    public Ingredient IngredientDataOnDemand.getNewTransientIngredient(int index) {
        Ingredient obj = new Ingredient();
        setName(obj, index);
        return obj;
    }
    
    public void IngredientDataOnDemand.setName(Ingredient obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Ingredient IngredientDataOnDemand.getSpecificIngredient(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Ingredient obj = data.get(index);
        return Ingredient.findIngredient(obj.getId());
    }
    
    public Ingredient IngredientDataOnDemand.getRandomIngredient() {
        init();
        Ingredient obj = data.get(rnd.nextInt(data.size()));
        return Ingredient.findIngredient(obj.getId());
    }
    
    public boolean IngredientDataOnDemand.modifyIngredient(Ingredient obj) {
        return false;
    }
    
    public void IngredientDataOnDemand.init() {
        data = Ingredient.findIngredientEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Ingredient' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.bulbview.recipeplanner.domain.Ingredient>();
        for (int i = 0; i < 10; i++) {
            Ingredient obj = getNewTransientIngredient(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
