// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bulbview.recipeplanner.domain;

import com.bulbview.recipeplanner.domain.Ingredient;
import com.bulbview.recipeplanner.domain.IngredientDataOnDemand;
import com.bulbview.recipeplanner.domain.IngredientQuantity;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect IngredientQuantityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IngredientQuantityDataOnDemand: @Component;
    
    private Random IngredientQuantityDataOnDemand.rnd = new SecureRandom();
    
    private List<IngredientQuantity> IngredientQuantityDataOnDemand.data;
    
    @Autowired
    private IngredientDataOnDemand IngredientQuantityDataOnDemand.ingredientDataOnDemand;
    
    public IngredientQuantity IngredientQuantityDataOnDemand.getNewTransientIngredientQuantity(int index) {
        IngredientQuantity obj = new IngredientQuantity();
        setAmount(obj, index);
        setIngredient(obj, index);
        return obj;
    }
    
    public void IngredientQuantityDataOnDemand.setAmount(IngredientQuantity obj, int index) {
        double amount = new Integer(index).doubleValue();
        obj.setAmount(amount);
    }
    
    public void IngredientQuantityDataOnDemand.setIngredient(IngredientQuantity obj, int index) {
        Ingredient ingredient = ingredientDataOnDemand.getRandomIngredient();
        obj.setIngredient(ingredient);
    }
    
    public IngredientQuantity IngredientQuantityDataOnDemand.getSpecificIngredientQuantity(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        IngredientQuantity obj = data.get(index);
        return IngredientQuantity.findIngredientQuantity(obj.getId());
    }
    
    public IngredientQuantity IngredientQuantityDataOnDemand.getRandomIngredientQuantity() {
        init();
        IngredientQuantity obj = data.get(rnd.nextInt(data.size()));
        return IngredientQuantity.findIngredientQuantity(obj.getId());
    }
    
    public boolean IngredientQuantityDataOnDemand.modifyIngredientQuantity(IngredientQuantity obj) {
        return false;
    }
    
    public void IngredientQuantityDataOnDemand.init() {
        data = IngredientQuantity.findIngredientQuantityEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'IngredientQuantity' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.bulbview.recipeplanner.domain.IngredientQuantity>();
        for (int i = 0; i < 10; i++) {
            IngredientQuantity obj = getNewTransientIngredientQuantity(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
