// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bulbview.recipeplanner.domain;

import com.bulbview.recipeplanner.domain.RecipeDataOnDemand;
import com.google.appengine.tools.development.testing.LocalServiceTestHelper;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RecipeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RecipeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RecipeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RecipeIntegrationTest: @Transactional;
    
    @Autowired
    private RecipeDataOnDemand RecipeIntegrationTest.dod;
    
    private static final LocalServiceTestHelper RecipeIntegrationTest.helper = new LocalServiceTestHelper(new com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig());
    
    @BeforeClass
    public static void RecipeIntegrationTest.setUp() {
        helper.setUp();
    }
    
    @AfterClass
    public static void RecipeIntegrationTest.tearDown() {
        helper.tearDown();
    }
    
    @Test
    public void RecipeIntegrationTest.testCountRecipes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", dod.getRandomRecipe());
        long count = com.bulbview.recipeplanner.domain.Recipe.countRecipes();
        org.junit.Assert.assertTrue("Counter for 'Recipe' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RecipeIntegrationTest.testFindRecipe() {
        com.bulbview.recipeplanner.domain.Recipe obj = dod.getRandomRecipe();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Recipe.findRecipe(id);
        org.junit.Assert.assertNotNull("Find method for 'Recipe' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Recipe' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RecipeIntegrationTest.testFindAllRecipes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", dod.getRandomRecipe());
        long count = com.bulbview.recipeplanner.domain.Recipe.countRecipes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Recipe', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.bulbview.recipeplanner.domain.Recipe> result = com.bulbview.recipeplanner.domain.Recipe.findAllRecipes();
        org.junit.Assert.assertNotNull("Find all method for 'Recipe' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Recipe' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RecipeIntegrationTest.testFindRecipeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", dod.getRandomRecipe());
        long count = com.bulbview.recipeplanner.domain.Recipe.countRecipes();
        if (count > 20) count = 20;
        java.util.List<com.bulbview.recipeplanner.domain.Recipe> result = com.bulbview.recipeplanner.domain.Recipe.findRecipeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Recipe' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Recipe' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RecipeIntegrationTest.testFlush() {
        com.bulbview.recipeplanner.domain.Recipe obj = dod.getRandomRecipe();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Recipe.findRecipe(id);
        org.junit.Assert.assertNotNull("Find method for 'Recipe' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRecipe(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Recipe' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RecipeIntegrationTest.testMerge() {
        com.bulbview.recipeplanner.domain.Recipe obj = dod.getRandomRecipe();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Recipe.findRecipe(id);
        boolean modified =  dod.modifyRecipe(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.bulbview.recipeplanner.domain.Recipe merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Recipe' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RecipeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", dod.getRandomRecipe());
        com.bulbview.recipeplanner.domain.Recipe obj = dod.getNewTransientRecipe(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Recipe' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Recipe' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional(propagation = Propagation.SUPPORTS)
    public void RecipeIntegrationTest.testRemove() {
        com.bulbview.recipeplanner.domain.Recipe obj = dod.getRandomRecipe();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Recipe' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Recipe.findRecipe(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Recipe' with identifier '" + id + "'", com.bulbview.recipeplanner.domain.Recipe.findRecipe(id));
    }
    
}
