// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bulbview.recipeplanner.domain;

import com.bulbview.recipeplanner.domain.ScheduleDataOnDemand;
import com.google.appengine.tools.development.testing.LocalServiceTestHelper;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ScheduleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ScheduleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ScheduleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ScheduleIntegrationTest: @Transactional;
    
    @Autowired
    private ScheduleDataOnDemand ScheduleIntegrationTest.dod;
    
    private static final LocalServiceTestHelper ScheduleIntegrationTest.helper = new LocalServiceTestHelper(new com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig());
    
    @BeforeClass
    public static void ScheduleIntegrationTest.setUp() {
        helper.setUp();
    }
    
    @AfterClass
    public static void ScheduleIntegrationTest.tearDown() {
        helper.tearDown();
    }
    
    @Test
    public void ScheduleIntegrationTest.testCountSchedules() {
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        long count = com.bulbview.recipeplanner.domain.Schedule.countSchedules();
        org.junit.Assert.assertTrue("Counter for 'Schedule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ScheduleIntegrationTest.testFindSchedule() {
        com.bulbview.recipeplanner.domain.Schedule obj = dod.getRandomSchedule();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Schedule.findSchedule(id);
        org.junit.Assert.assertNotNull("Find method for 'Schedule' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Schedule' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ScheduleIntegrationTest.testFindAllSchedules() {
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        long count = com.bulbview.recipeplanner.domain.Schedule.countSchedules();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Schedule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.bulbview.recipeplanner.domain.Schedule> result = com.bulbview.recipeplanner.domain.Schedule.findAllSchedules();
        org.junit.Assert.assertNotNull("Find all method for 'Schedule' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Schedule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ScheduleIntegrationTest.testFindScheduleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        long count = com.bulbview.recipeplanner.domain.Schedule.countSchedules();
        if (count > 20) count = 20;
        java.util.List<com.bulbview.recipeplanner.domain.Schedule> result = com.bulbview.recipeplanner.domain.Schedule.findScheduleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Schedule' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Schedule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ScheduleIntegrationTest.testFlush() {
        com.bulbview.recipeplanner.domain.Schedule obj = dod.getRandomSchedule();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Schedule.findSchedule(id);
        org.junit.Assert.assertNotNull("Find method for 'Schedule' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySchedule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Schedule' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ScheduleIntegrationTest.testMerge() {
        com.bulbview.recipeplanner.domain.Schedule obj = dod.getRandomSchedule();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Schedule.findSchedule(id);
        boolean modified =  dod.modifySchedule(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.bulbview.recipeplanner.domain.Schedule merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Schedule' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ScheduleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", dod.getRandomSchedule());
        com.bulbview.recipeplanner.domain.Schedule obj = dod.getNewTransientSchedule(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Schedule' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Schedule' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional(propagation = Propagation.SUPPORTS)
    public void ScheduleIntegrationTest.testRemove() {
        com.bulbview.recipeplanner.domain.Schedule obj = dod.getRandomSchedule();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Schedule' failed to provide an identifier", id);
        obj = com.bulbview.recipeplanner.domain.Schedule.findSchedule(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Schedule' with identifier '" + id + "'", com.bulbview.recipeplanner.domain.Schedule.findSchedule(id));
    }
    
}
