// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bulbview.recipeplanner.domain;

import java.lang.String;

privileged aspect Ingredient_Roo_JavaBean {
    
    public String Ingredient.getName() {
        return this.name;
    }
    
    public void Ingredient.setName(String name) {
        this.name = name;
    }
    
}
